config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'

  get 'posts/show'

  get 'posts/edit'

  resources :tags
  resources :posts

  resources :events
  resources :users
  get 'last_event', to: 'events#last_event'

  get 'contatti', to: 'contact#index'
  get 'signup' => 'users#new'
    
  get 'home/index'

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title,:body, presence: :true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  #validates :name, presence: true
  #validates :email, presence: true

  validates :name, presence: true, length:  {maximum: 50}
  validates :surname, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format:  {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
 

  has_secure_password 

  has_many :posts, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end
 
=begin 
  def last_event
    @last_event = Event.last
  end
=end


  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, { tag_ids:[]})
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Social Network 2015"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/index.html.erb
<%= provide(:title, "Contatti")%>
<div class="col-md-12">
<h1>Pagina Contatti Social Network</h1>
<p></p>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Titolo", class: "col-md-2 control-label" %>
    <div class="col-md-10"> 
      <%= f.text_field :title, class: "form-control", placeholder:"Title Event" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :body, "Body", class: "col-md-2 control-label" %><br>
    <div class="col-md-10">
      <%= f.text_area :body, class: "form-control", placeholder:"Body event" %>
    </div>
  </div>
    
    <div class="col-md-2"> 
      <%= f.submit class: "btn btn-default" %>
    </div>

<% end %>

app/views/events/edit.html.erb
<%= provide(:title, "Edit #{@event.title} ")%>
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= provide(:title, "Events")%>

<div class="col-md-12">
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id%></td>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
          
        <td><%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, event %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_event_path(event) %></td>
        <td><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: "btn btn-default" %>
<br>
<!--
<#%= link_to 'Last Event', last_event_path%>
-->
</div>

app/views/events/last_event.html.erb
<div class="col-md-12">
<p> <%= @last_event.title %></p>
</div>

app/views/events/new.html.erb
<%= provide(:title, "Add new event")%>

<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= provide(:title, "#{@event.title}")%>



<p id="notice"><%= notice %></p>

<div class="col-md-6">  

  <h4><%= @event.title %></h4>

  <p>
    <%= @event.body %>
  </p>

  <hr>

  <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-default" %> |
  <%= link_to 'Back', events_path, class: "btn btn-default" %>

</div>

app/views/home/index.html.erb
<%= provide(:title, "Home")%>

<div class="col-md-12">
  <h1>SOCIAL NETWORK 2015</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- NavBar -->
<%= render partial: "shared/menu"%>
<!-- NavBar -->


<div class="container">
  <div class="row"> 
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  
  <hr/>
  <div class="field">
    <% Tag.all.each do |tag|%>
    <div class="checkbox">
      <%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>              
      <%= tag.name %>
    </div>
    <%end%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.user_id %></td>
        <%post.tags.each do |pt|%>
          <td><%= pt.name%></td>
        <%end%>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
      <%= link_to "Social Network 2015", root_path, class: "navbar-brand"%>  
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path%></li>
        <!--
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contatti", contatti_path%></li>
        <li><%=link_to "Eventi", events_path %></li>
        <li><%= link_to "SignUp", signup_path%></li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/new.html.erb
<%provide(:title, "Signup")%>

<h1>Sign Up</h1>
<p></p>